// Generated by CoffeeScript 1.4.0
(function() {
  var instagram_feed, pics;

  instagram_feed = (function() {
    var option, value;

    function instagram_feed(params) {
      this.options = {
        user_id: 'USER_ID',
        access_token: 'ACCESS_TOKEN',
        target: 'instafeed',
        get: 'popular',
        resolution: 'thumbnail',
        sortBy: 'most-recent',
        links: true,
        limit: 15,
        mock: false
      };
    }

    if (typeof params === 'object') {
      for (option in params) {
        value = params[option];
        instagram_feed.options = value;
      }
    }

    return instagram_feed;

  })();

  pics = new instagram_feed({
    user_id: 'jimmybillings',
    access_token: '1234',
    target: 'turkey',
    get: 'photos',
    resolution: 'big',
    sortBy: 'abc',
    links: true,
    limit: 15,
    mock: false
  });

  console.log(pics);


}).call(this);
