// Generated by CoffeeScript 1.5.0
(function() {
  var Instafeed, feed;

  Instafeed = (function() {

    function Instafeed(params) {
      var option, value;
      this.options = {
        user_id: "USER_ID",
        access_token: "ACCESS_TOKEN"
      };
      if (typeof params === "object") {
        for (option in params) {
          value = params[option];
          this.options[option] = value;
        }
      }
    }

    Instafeed.prototype._urlBuilder = function() {
      var accessToken, baseUrl, callback, count, media, user;
      baseUrl = "https://api.instagram.com/v1/users/";
      user = "v1/users/" + this.options.user_id;
      media = "/media/recent/";
      accessToken = "?access_token=" + this.options.access_token;
      count = "&count=100";
      callback = "&callback=feed._Feedy";
      this.script = "" + baseUrl + user + media + accessToken + count + callback;
    };

    Instafeed.prototype._buildScript = function() {
      var instaScript;
      instaScript = document.createElement('script');
      instaScript.src = this.script;
      document.getElementsByTagName('head')[0].appendChild(instaScript);
    };

    Instafeed.prototype._run = function() {
      this._urlBuilder();
      this._buildScript();
    };

    return Instafeed;

  })();

  feed = new Instafeed({
    user_id: "45200455",
    access_token: "45200455.7ff53ac.2deb72ff63a64b8ab7f75afb501868d8"
  });

  feed._run();

}).call(this);
